name: android-signing
version: 1.0.0
icon: "golang-icon.svg"

inputs:
- name: ANDROID_BUILD_TOOLS
  type: string
  required: true

- name: ANDROID_SDK_HOME
  type: string
  required: true

- name: SIGN_FILE_PATTERN
  type: string
  value: '*-unsigned.apk'
  required: false


script: |
  cd $FLOWCI_GIT_REPO
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/android-signing
  ${plugindir}/sign.sh